### PR TITLE
Fix auto-closing quotes for heredocs

### PR DESCRIPTION
**Pull request by jarrodldavis**
Add triple double quotes (`"""`) as an auto-closing pair in the Elixir language configuration to prevent extra quotes from being inserted when starting a heredoc string.

### CODE REVIEW

**Comment by jayjun** [comment]
Can you make it work with sigils?

sigil

Ideally typing `~` `L` `"` `"` `"` auto closes with `"""`.

**Comment by jarrodldavis** [comment]
Sure thing, but the list of applicable sigils will have to be hard coded (I don’t think VS Code allows something like “a tilde followed by any letter and three double quotes”). I’m new to Elixir, so what sigils (besides `~L`) are commonly used with triple double-quotes?

**Comment by jayjun** [comment]
`sigil_*` macros provided by Elixir are in [`Kernel`](https://hexdocs.pm/elixir/Kernel.html#sigil_C/2). [`sigil_L`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Helpers.html#sigil_L/2) is provided by LiveView. These should cover most cases.

**Comment by axelson** [comment]
@jarrodldavis emacs-elixir has a good list that was just updated for ~L: https://github.com/elixir-editors/emacs-elixir/pull/454/files

**Comment by jarrodldavis** [comment]
@axelson @jayjun I've updated the auto-closing pairs configuration with sigils for single double quotes and triple double quotes.

**Comment by jayjun** [comment]
Sweet, it works perfectly.

**Pull request merged**
