### PR TITLE
Integrate CI

### PR DESCRIPTION
**Pull request by niku**
related #28

You can check test results sample
- [succeed](https://github.com/niku/vscode-elixir-ls/commit/18d8730d2ed4a7995c8066ecf12add3e77edf46a/checks?check_suite_id=404079724)
- [failed](https://github.com/niku/vscode-elixir-ls/commit/bec1cec6cff396011426de50f2f3bb612cb3e7e5/checks?check_suite_id=404073165)

# Why Github Actions?

In [Continuous Integration](https://code.visualstudio.com/api/working-with-extensions/continuous-integration), there have samples Azure Pipelines and Travis CI.
I think Github Actions is more fit because of no need 3rd party account.

# What lacks?

Currently, I only test node 8 and elixir 1.9.4 on linux environment.
Should I add matrix test such as node 8, 10, 12, elixir 1.7, 1.8, 1.9 and on windows, osx, linux?

### CODE REVIEW

**Comment by axelson** [comment]
It would be nice to add at least a partial matrix, especially the three different platforms.

**Comment by niku** [comment]
Sure. I'll try setting it.

**Comment by axelson** [comment]
But I think we can add that in a later pass so I'm going to go ahead and merge this now.

**Comment by niku** [comment]
Sure. Thanks!

**Pull request merged**
