### PR TITLE
Integrate Code lens with testing tab

### PR DESCRIPTION
**Pull request by Carl-Foster**
- Also allow doctest to be tested

### CODE REVIEW

**Comment by lukaszsamson** [comment]
Please revert formatting changes. Open a separate PR with linting fixes

**Comment by Carl-Foster** [comment]
> Please revert formatting changes. Open a separate PR with linting fixes

Formatting fixes are in #294

**Comment by lukaszsamson** [comment]
Please revert elixir-ls submodule changes. Create a separate PR to elixir-ls repo and link it here

**Comment by Carl-Foster** [comment]
Removed the elixir-ls submodule updates.

**Review by CPNJMD — APPROVED** [review]
,

**Comment by lukaszsamson** [comment]
Thanks @Carl-Foster

**Pull request merged**
