### PR TITLE
Add function definiton scope

### PR DESCRIPTION
**Pull request by CaiqueMitsuoka**
## Objective

Add a scope for function definition which combined with the other token can be used to differentiate definition from calls.

Function definition with different style from a function call

## Details

Add to the function definition rule the `meta.definition.function.elixir` scope for function with and without parameters.

Function call with only entity.name.function scope
Function definition with entity.name.function and meta.definition.function

The theme is defined as below

```json
{
  "name": "Function name",
  "scope": "entity.name.function",
  "settings": {
    "fontStyle": "",
    "foreground": "#ff6333"
  }
},
{
  "name": "Function definition name",
  "scope": [
    "meta.definition.function entity.name.function"
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#ffd400"
  }
}
```

cc @axelson @thiagomajesk

### CODE REVIEW

**Comment by thiagomajesk** [comment]
Looks good @CaiqueMitsuoka!

Out of curiosity, is there any particular reason why `meta.definition.function` was prefered over `entity.name.function-call.elixir` like Ruby's TextMate grammar? (I guess it has semantic reasoning behind)

Also, a followup on this: https://github.com/elixir-lsp/vscode-elixir-ls/issues/22#issuecomment-570805792, do you think we could do something about it in this batch?

**Comment by thiagomajesk** [comment]
@CaiqueMitsuoka @axelson 
Hi guys, how are you? It's been some time since the last update and I was wondering if there's anything I can do to help to keep things going.

**Comment by axelson** [comment]
Adding a name makes sense, but I'm not familiar enough with syntax grammars to know what the correct name is. @thiagomajesk is there some general reference that can be followed? Or do we have to mainly look at what other grammars (like Ruby's TextMate grammar) define?

**Comment by thiagomajesk** [comment]
AFAIK, there's this: https://macromates.com/manual/en/language_grammars. 
I don't know how much other language grammars rely strictly on the docs for naming, though.

**Comment by axelson** [comment]
Superseded by #40

**Pull request closed without merging**
